"""
This type stub file was generated by pyright.
"""

def _get_type_cons(type_):
    """More spaghetti logic for 3.6 vs. 3.7"""
    ...

def _get_type_origin(type_):
    """Some spaghetti logic to accommodate differences between 3.6 and 3.7 in
    the typing api"""
    ...

def _hasargs(type_, *args):
    ...

def _isinstance_safe(o, t):
    ...

def _issubclass_safe(cls, classinfo):
    ...

def _is_new_type_subclass_safe(cls, classinfo):
    ...

def _is_new_type(type_):
    ...

def _is_optional(type_):
    ...

def _is_mapping(type_):
    ...

def _is_collection(type_):
    ...

def _is_nonstr_collection(type_):
    ...

def _timestamp_to_dt_aware(timestamp: float):
    ...

