"""
This type stub file was generated by pyright.
"""

import asyncio
from ._scheduler import Scheduler
from typing import Any, Optional

"""Jobs scheduler for managing background task (asyncio).

The library gives controlled way for scheduling background tasks for
asyncio applications.

"""
__version__ = '0.2.2'
async def create_scheduler(*, close_timeout=..., limit=..., pending_limit=..., exception_handler: Optional[Any] = ...):
    ...

__all__ = ('create_scheduler', )
