"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Optional

class BaseProtocol(asyncio.Protocol):
    __slots__ = ...
    def __init__(self, loop: asyncio.AbstractEventLoop) -> None:
        self.transport = ...
    
    def pause_writing(self) -> None:
        ...
    
    def resume_writing(self) -> None:
        ...
    
    def pause_reading(self) -> None:
        ...
    
    def resume_reading(self) -> None:
        ...
    
    def connection_made(self, transport: asyncio.BaseTransport) -> None:
        self.transport = ...
    
    def connection_lost(self, exc: Optional[BaseException]) -> None:
        self.transport = ...
    
    async def _drain_helper(self) -> None:
        ...
    


