"""
This type stub file was generated by pyright.
"""

import asyncio
import socket

"""Helper methods to tune a TCP connection"""
__all__ = ('tcp_keepalive', 'tcp_nodelay', 'tcp_cork')
if hasattr(socket, 'TCP_CORK'):
    CORK = socket.TCP_CORK
else:
    CORK = socket.TCP_NOPUSH
    CORK = None
if hasattr(socket, 'SO_KEEPALIVE'):
    def tcp_keepalive(transport: asyncio.Transport) -> None:
        ...
    
else:
    def tcp_keepalive(transport: asyncio.Transport) -> None:
        ...
    
def tcp_nodelay(transport: asyncio.Transport, value: bool) -> None:
    ...

def tcp_cork(transport: asyncio.Transport, value: bool) -> None:
    ...

