"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any, List, Optional
from .abc import AbstractStreamWriter
from .http_parser import RawRequestMessage
from .streams import StreamReader
from .web_protocol import RequestHandler, _RequestFactory, _RequestHandler
from .web_request import BaseRequest

"""Low level HTTP server."""
__all__ = ('Server', )
class Server:
    def __init__(self, handler: _RequestHandler, *, request_factory: Optional[_RequestFactory] = ..., loop: Optional[asyncio.AbstractEventLoop] = ..., **kwargs: Any) -> None:
        self.requests_count = ...
        self.request_handler = ...
        self.request_factory = ...
    
    @property
    def connections(self) -> List[RequestHandler]:
        ...
    
    def connection_made(self, handler: RequestHandler, transport: asyncio.Transport) -> None:
        ...
    
    def connection_lost(self, handler: RequestHandler, exc: Optional[BaseException] = ...) -> None:
        ...
    
    def _make_request(self, message: RawRequestMessage, payload: StreamReader, protocol: RequestHandler, writer: AbstractStreamWriter, task: asyncio.Task[None]) -> BaseRequest:
        ...
    
    async def shutdown(self, timeout: Optional[float] = ...) -> None:
        ...
    
    def __call__(self) -> RequestHandler:
        ...
    


