"""
This type stub file was generated by pyright.
"""

LCD_CLEARDISPLAY = 1
LCD_RETURNHOME = 2
LCD_ENTRYMODESET = 4
LCD_DISPLAYCONTROL = 8
LCD_CURSORSHIFT = 16
LCD_FUNCTIONSET = 32
LCD_SETCGRAMADDR = 64
LCD_SETDDRAMADDR = 128
LCD_ENTRYRIGHT = 0
LCD_ENTRYLEFT = 2
LCD_ENTRYSHIFTINCREMENT = 1
LCD_ENTRYSHIFTDECREMENT = 0
LCD_DISPLAYON = 4
LCD_CURSORON = 2
LCD_BLINKON = 1
LCD_DISPLAYMOVE = 8
LCD_CURSORMOVE = 0
LCD_MOVERIGHT = 4
LCD_MOVELEFT = 0
LCD_8BITMODE = 16
LCD_4BITMODE = 0
LCD_2LINE = 8
LCD_1LINE = 0
LCD_5x10DOTS = 4
LCD_5x8DOTS = 0
COMMAND = 0
DATA = 1
FOUR_BITS = 2
LCD_BACKLIGHT = 8
LCD_NOBACKLIGHT = 0
HOME_CLEAR_EXEC = 2000
EXEC_TIME = 37
En = 4
Rw = 2
Rs = 1
cursor_row_offset = [0, 64, 20, 84]
class LiquidCrystalDriver:
    def __init__(self, i2c_path: str, i2c_address: int = ...):
        self.i2c_device = ...
    
    def clear(self):
        ...
    
    def __write_four_bits(self, data: int):
        ...
    
    def __write(self, command: int, mode: int = ...):
        ...
    
    def set_cursor(self, row: int, col: int):
        ...
    
    def display_at_position(self, display: str, row: int, col: int):
        ...
    
    def display(self, display: str):
        ...
    
    def set_blacklight(self, on: bool):
        ...
    
    def set_blink(self, on: bool):
        ...
    
    def scroll_display_right(self):
        ...
    


