"""
This type stub file was generated by pyright.
"""

I2C_SLAVE = 1795
class I2C:
    def __init__(self, i2c_path: str, i2c_address: int = ...):
        ...
    
    def write_command_arg(self, command: int, arg: int):
        ...
    
    def write_command(self, command: int):
        ...
    
    def read(self) -> int:
        ...
    
    def read_data(self, command: int) -> int:
        ...
    


