"""
This type stub file was generated by pyright.
"""

"""
Library meta information.

This module must be stand-alone executable.
"""
__title__ = "aiohttp-cors"
__version__ = "0.7.0"
__author__ = "Vladimir Rutsky and aio-libs team"
__email__ = "vladimir@rutsky.org"
__summary__ = "CORS support for aiohttp"
__uri__ = "https://github.com/aio-libs/aiohttp-cors"
__license__ = "Apache License, Version 2.0"
__copyright__ = "2015-2018 {}".format(__author__)
