"""
This type stub file was generated by pyright.
"""

from .preflight_handler import _PreflightHandler

def custom_cors(config):
    ...

class CorsViewMixin(_PreflightHandler):
    cors_config = ...
    @classmethod
    def get_request_config(cls, request, request_method):
        ...
    
    async def _get_config(self, request, origin, request_method):
        ...
    
    async def options(self):
        ...
    


