"""
This type stub file was generated by pyright.
"""

from aiohttp import web

_TRUE = "true"
class _PreflightHandler:
    @staticmethod
    def _parse_request_method(request: web.Request):
        """Parse Access-Control-Request-Method header of the preflight request
        """
        ...
    
    @staticmethod
    def _parse_request_headers(request: web.Request):
        """Parse Access-Control-Request-Headers header or the preflight request

        Returns set of headers in upper case.
        """
        ...
    
    async def _get_config(self, request, origin, request_method):
        ...
    
    async def _preflight_handler(self, request: web.Request):
        """CORS preflight request handler"""
        ...
    


